/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./components/AppLogo.vue')['default']
    PhotoPortrait: typeof import('./components/PhotoPortrait.vue')['default']
    ProjectItem: typeof import('./components/ProjectItem.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAppBar: typeof import('./components/TheAppBar.vue')['default']
    TheProjects: typeof import('./components/TheProjects.vue')['default']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VChip: typeof import('vuetify/components')['VChip']
    VDialog: typeof import('vuetify/components')['VDialog']
    VImg: typeof import('vuetify/components')['VImg']
    VProgressCircular: typeof import('vuetify/components')['VProgressCircular']
  }
}
